language: node_js
node_js:
- '10'
cache:
  bundler: true
jobs:
  include:
    - stage: Lint
      script: npm run lint
    - stage: Test & Coverage
      script: npm run coverage
    - stage: Build & Deploy
      script: npm run build && npm run deploy
      if: branch = master
env:
  global:
    secure: G+1WTQEBxZRsLIyEEf4HcCIJVH4+60jAMmL/QwT8+qFmwSOpeLZUl/jq3mNuOrrpP3GNZLS6tZOksR4cKzqaNYEnBJnL8RKDEHiSGDX/JG1IteQU8cYWCWyeFFMjWz3c8EOZzcE9TqrppemxKUZWt1VHDRyOb3yBKwjdndThwUHG0qs1mjioLDJBMRNADSyKZBprWuVasZIZjYrV6Kya3CNkacWhuLAVyejBDEB/XK3CMpy0gMawuw3HP3wfAQtoGf/XR4fQB7M7ROMJa8L53DhhmWrkgF/YevipolSHtctUrMvPifY86I9jvWuMXQYShK5yqxmi6bcy3brItSJxHSlb0HxDZ13gF1m3jWVfJbgBN4VXTDdE/QDQYUGwAghaH+ENZv9Fv+86l55ogDKg8iUBcFTDuPtz2w+HJFU65PLV8YLBDfv7URpRAHZd15iNbXlv+vvN8k2WyB+c3cgag4itR3b7B9Xa6AvEFC7AAbiS4xM/NhVrD9DJLuRN2N7MDzVUOvpnCCz6JPv7WQwMYe+k/0RKn/c+g7OUdtkZIaBn/re9eSvu9t0tY3ZRG4r7SsBifegSqJse1CVf+svKIQTIb3mdXyEy1OeURRljyDry2KPzHStPSlaBeyq4idSDHtc3uT85uCX2fHueGdWTFC+rWSfvLX2qa7T+E8sz/I4=
