export enum MessageReceiveType {
	UPDATE_GRAVITY = 'UPDATE_GRAVITY',
	UPDATE_ELECTO = 'UPDATE_ELECTRO',
	UPDATE_BOUNDARY_SIZE = 'UPDATE_BOUNDARY_SIZE',
	UPDATE_BOUNDARY_TYPE = 'UPDATE_BOUNDARY_TYPE',
	ADD_PARTICLE = 'ADD_PARTICLE',
	REMOVE_PARTICLE = 'REMOVE_PARTICLE',
	UPDATE_STEP_SIZE = 'UPDATE_STEP_SIZE',
	CHANGE_COLLISION_TYPE = 'CHANGE_COLLISION_TYPE',
}
